server:
  port: 9003
spring:
  application:
    name: tensquare-recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.100:3306/tensquare_qa?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
  devtools:
    restart:
      enabled: true